
server:
  port: ${API_GATEWAY_APP_PORT:80}

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server-app:8761/eureka

spring:
  application:
    name: api-gateway-app
  cloud:
    gateway:
      routes:
        - id: user
          uri: lb://CUSTOMER-APP
          predicates:
            - Path=/user/**
        - id: auth
          uri: lb://CUSTOMER-APP
          predicates:
            - Path=/auth/**







