
server:
  port: ${API_GATEWAY_APP_PORT:80}

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server-app:8761/eureka

spring:
  application:
    name: api-gateway-app
  cloud:
    gateway:
      routes:
        - id: customer-app
          uri: lb://CUSTOMER-APP
          predicates:
            - Path=/user/**, Path=/auth/**








